### ISSUE TITLE
Cron-based reload of Dovecot en Postfix configs fail

### ISSUE THREAD

**Issue by woosting** [SomethingWithHorizons/mailserver#1]
### Description:
Cron-jobs to auto-reload Dovecot en Postfix configuration files (for the [mailserver certificate renewal](https://github.com/SomethingWithHorizons/mailserver/wiki/Mail-server_SSL-certificate-configuration)) fail with the error: `/bin/sh: 1: service: not found`.

### Workaround:
Periodically (weekly?) issue manually:
```shell
service postfix reload
service dovecot reload
```

### Root-cause:
ASSUMPTION: `service` somehow not in the path/environment used by Cron?

### Proposed solution:
Use absolute paths in crontab,  e.g.:
```
@weekly /usr/sbin/service postfix reload
@weekly /usr/sbin/service dovecot reload
```

**Comment by kusozayka** [comment]
Seems legit. Feel free to change! Using absolute paths is in general better anyway, especially in crontabs.

**Comment by woosting** [comment]
### Action taken:
Fixed by adding /usr/sbin/ to the cron command (as suggested above):
```
# m h  dom mon dow   command
54 * * * * /usr/sbin/service postfix reload
54 * * * * /usr/sbin/service dovecot reload
53 * * * * service postfix reload
53 * * * * service dovecot reload
```

### Result:
```
# grep CRON /var/log/syslog
Apr 22 16:53:01 ##### CRON[631]: (root) CMD (service postfix reload)
Apr 22 16:53:01 ##### CRON[632]: (root) CMD (service dovecot reload)
Apr 22 16:54:01 ##### CRON[664]: (root) CMD (/usr/sbin/service postfix reload)
Apr 22 16:54:01 ##### CRON[665]: (root) CMD (/usr/sbin/service dovecot reload)
```
So: All 4 got executed by Cron (hence the log-entries). The upper two resulting in the error-email (as expected the bug), latter stayed "silent" (so the seemed to have executed correctly).

### Conclusion:
It _seems_ operational now, but I am not sure how to verify 100% (looking for conclusive output in some way).

### Follow-up question:
Any suggestions on how to check to know for sure (e.g. what log-file to check, and looking for what string exactly)?

**Comment by kusozayka** [comment]
You can check if you see any reload kind of messages of `dovecot` and/or `postfix` within `/var/log/mail.log`, beside this there's not much to validate. If the reload fails you probably would receive a mail from the cron daemon.

**Comment by woosting** [comment]
Fix confirmed:
```
Apr 29 00:00:02 user dovecot: master: Warning: SIGHUP received - reloading configuration
Apr 29 00:00:03 user postfix/master[432]: reload -- version 3.1.8, configuration /etc/postfix
```
