### ISSUE TITLE
Only 2 concurrent login sessions available

### ISSUE THREAD

**Issue by woosting** [SomethingWithHorizons/mailserver#3]
Use a phone and a desktop client and all slots are filled.

How to configure the mailserver (Dovecot?) as such that more than 2 login session slots are available at the same time?

**Comment by kusozayka** [comment]
The default limit is actually 10, but some clients tend to use more connections (e.g. [Thunderbird](https://www.electrictoolbox.com/thunderbird-exceeded-maximum-connections-imap-server/)). Anyhow...

You can edit `/etc/dovecot/conf.d/20-imap.conf` and uncomment/increase the value of  `mail_max_userip_connections`.

**Comment by woosting** [comment]
Sounds legit, thanks!
