### ISSUE TITLE
opendkim service will fail to start due to improperly managed dependency towards mysql

### ISSUE THREAD

**Issue by jvberkel** [SomethingWithHorizons/mailserver#4]
During operational use, mail scores on mail-tester.com dropped due to DKIM not being properly applied because the Opendkim service did not properly start after system reboots. This prooved to be caused by Mariadb not being available at opendkim start.

I added a ["quick fix" in the guide that extends the systemd configuration file for opendkim](https://github.com/SomethingWithHorizons/mailserver/wiki/Mail-server_DKIM-signing) to start the service after a 5 seconds time-delay, which provides MariaDB with time to start up. 

A proper fix would however be to explicitly manage the startup-order-dependency between opendkim and MariaDB!

**Comment by kusozayka** [comment]
This can be achieved by using the `After` specification of systemd, for Ubuntu that would mean editing `/etc/systemd/system/multi-user.target.wants/opendkim.service` and change:
```diff
- After=network.target nss-lookup.target
+ After=network.target nss-lookup.target mysqld.service
```

**Comment by jvberkel** [comment]
Fix is verified OK. Suggest to not alter the suggested configuration as it refers to a default configuration file and - as far as I understood - i[t is better practice to override defaults via custom configurations since defaults can be overridden during software updates](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/sect-Managing_Services_with_systemd-Unit_Files#sect-Managing_Services_with_systemd-Unit_File_Modify).

Suggested filename: `/etc/systemd/system/opendkim.service.d/opendkim_mysql_dep.conf`

Applicable edit: 

```diff
+[Unit]
+After=network.target nss-lookup.target mysqld.service
```

Please review the fix as I have applied it to the new [mail guide](https://mailguide.woosting.nl:8443/mailserver/email-acceptance/dkim) and close this ticket when deemed acceptable

**Comment by kusozayka** [comment]
It's correct that directory `/etc/systemd/system/opendkim.service.d` doesn't exist by default (and should be created manually?)

Also, are `network.target nss-lookup.target` required in this case? Or do need to exist because you override the `After` section as whole?

**Comment by Sm0ke0ut** [comment]
@
